/* AUTOGENERATED from sdk/kapi.json - DO NOT EDIT */
extern const unsigned int __os32_abi_1_mem_3_fmt_4;
static const unsigned int os32_unit_note[] __attribute__((used,section(".os32_generations"))) = {4,1,3,1};
static const void *const os32_unit_ref __attribute__((used,section(".os32_generation_ref"))) = &__os32_abi_1_mem_3_fmt_4;
