/* AUTOGENERATED FILE - DO NOT EDIT */
#ifndef OS32_KAPI_GENERATED_H
#define OS32_KAPI_GENERATED_H

typedef struct {
    u32 magic;
    u32 version;
    void (__cdecl *gfx_init)(void);
    void (__cdecl *gfx_init_200)(void);
    void (__cdecl *gfx_shutdown)(void);
    void (__cdecl *gfx_present)(void);
    int (__cdecl *kbd_trygetchar)(void);
    void * (__cdecl *mem_alloc)(u32 size);
    void (__cdecl *mem_free)(void *ptr);
    u32 (__cdecl *get_tick)(void);
    void (__cdecl *kprintf)(u8 attr, const char *fmt, ...);
    int (__cdecl *sys_unlink)(const char *path);
    int (__cdecl *sys_rename)(const char *oldpath, const char *newpath);
    int (__cdecl *sys_mkdir)(const char *path);
    int (__cdecl *sys_ls)(const char *path, void *cb, void *ctx);
    u32 (__cdecl *kmalloc_total)(void);
    u32 (__cdecl *kmalloc_used)(void);
    u32 (__cdecl *kmalloc_free)(void);
    int (__cdecl *paging_enabled)(void);
    void (__cdecl *rtc_read)(void *rtc_time);
    void (__cdecl *tvram_clear)(void);
    void (__cdecl *tvram_putchar_at)(int x, int y, char ch, u8 attr);
    void (__cdecl *tvram_putkanji_at)(int x, int y, u16 jis, u8 attr);
    void (__cdecl *tvram_scroll)(void);
    int (__cdecl *kbd_getchar)(void);
    int (__cdecl *kbd_getkey)(void);
    int (__cdecl *kbd_trygetkey)(void);
    int (__cdecl *sys_mount)(const char *prefix, const char *dev, const char *fs);
    void (__cdecl *sys_umount)(const char *prefix);
    int (__cdecl *sys_is_mounted)(const char *prefix);
    int (__cdecl *sys_chdir)(const char *path);
    const char * (__cdecl *sys_getcwd)(void);
    const char * (__cdecl *vfs_devname)(const char *prefix);
    int (__cdecl *vfs_sync)(void);
    int (__cdecl *sys_rmdir)(const char *path);
    void (__cdecl *serial_init)(u32 baud);
    void (__cdecl *serial_puts)(const char *s);
    int (__cdecl *serial_getchar)(void);
    int (__cdecl *serial_putchar)(u8 ch);
    int (__cdecl *serial_trygetchar)(void);
    int (__cdecl *serial_is_initialized)(void);
    int (__cdecl *exec_run)(const char *path);
    int (__cdecl *dev_count)(void);
    int (__cdecl *dev_get_info)(int idx, char *name, int nm, int *type, u32 *sects);
    void (__cdecl *fm_startup_sound)(void);
    void (__cdecl *fm_play_mml)(const char *mml);
    int (__cdecl *np2_detect)(void);
    void (__cdecl *np2_get_version)(char *buf, int size);
    void (__cdecl *np2_get_cpu)(char *buf, int size);
    void (__cdecl *np2_get_clock)(char *buf, int size);
    int (__cdecl *np2_check_hostdrv)(char *buf, int size);
    void (__cdecl *ide_init)(void);
    int (__cdecl *ide_drive_present)(int drv);
    int (__cdecl *ide_identify)(int drv, void *info);
    int (__cdecl *ide_read_sector)(int drv, u32 lba, void *buf);
    const char * (__cdecl *path_get_drive)(void);
    const char * (__cdecl *path_get_cwd)(void);
    int (__cdecl *path_set_drive)(const char *d);
    void (__cdecl *path_set_cwd)(const char *p);
    void (__cdecl *path_parse)(const char *input, void *result);
    int (__cdecl *ext2_format)(int drv, u32 sectors);
    void (__cdecl *kcg_init)(void);
    void (__cdecl *kcg_set_scale)(int s);
    void (__cdecl *buz_on)(void);
    void (__cdecl *buz_off)(void);
    void (__cdecl *rshell_set_active)(int active);
    int (__cdecl *ide_write_sector)(int drv, u32 lba, const void *buf);
    int (__cdecl *ide_write_sectors)(int drv, u32 lba, u32 cnt, const void *buf);
    void (__cdecl *sys_reboot)(void);
    void (__cdecl *sys_halt)(void);
    void (__cdecl *shell_putchar)(char ch, u8 attr);
    void (__cdecl *shell_print_utf8)(const char *utf8_str, u8 color);
    int (__cdecl *console_get_cursor_x)(void);
    int (__cdecl *console_get_cursor_y)(void);
    void (__cdecl *console_set_cursor)(int x, int y);
    int (__cdecl *sys_open)(const char *path, int mode);
    void (__cdecl *sys_close)(int fd);
    int (__cdecl *sys_read)(int fd, void *buf, u32 size);
    int (__cdecl *sys_write)(int fd, const void *buf, u32 size);
    int (__cdecl *sys_lseek)(int fd, int offset, int whence);
    void (__cdecl *console_get_size)(int *w, int *h);
    u32 (__cdecl *kbd_get_modifiers)(void);
    u32 (__cdecl *sys_get_mem_kb)(void);
    os_time_t (__cdecl *sys_time)(void);
    void (__cdecl *gfx_hardware_scroll)(int lines);
    void (__cdecl *gfx_present_rect)(int x, int y, int w, int h);
    void (__cdecl *sys_exit)(int status);
    int (__cdecl *sys_isatty)(int fd);
    int (__cdecl *sys_stat)(const char *path, OS32_Stat *buf);
    int (__cdecl *sys_fstat)(int fd, OS32_Stat *buf);
    void (__cdecl *gfx_set_palette)(int idx, u8 r, u8 g, u8 b);
    void (__cdecl *gfx_get_palette)(int idx, u8 *r, u8 *g, u8 *b);
    void (__cdecl *gfx_get_framebuffer)(void *fb);
    void (__cdecl *gfx_add_dirty_rect)(int x, int y, int w, int h);
    void (__cdecl *gfx_present_dirty)(void);
    void (__cdecl *gfx_present_nosync)(void);
    void (__cdecl *gfx_present_raster)(void *table);
    void (__cdecl *kcg_read_ank)(u8 ch, u8 *buf);
    void (__cdecl *kcg_read_kanji)(u16 jis_code, u8 *buf);
    void * (__cdecl *sys_shm_alloc)(int blocks);
    int (__cdecl *sys_shm_lock)(void *ptr);
    int (__cdecl *sys_shm_free)(void *ptr);
    int (__cdecl *ime_getchar)(void);
    int (__cdecl *ime_trygetchar)(void);
    void (__cdecl *ime_toggle)(void);
    int (__cdecl *ime_is_active)(void);
    void (__cdecl *ime_set_mode)(int mode);
    int (__cdecl *ime_get_mode)(void);
    int (__cdecl *ime_getkey)(void);
    int (__cdecl *sys_redirect_fd)(int fd, const char *path, int mode);
    void (__cdecl *sys_reset_redirect)(int fd);
    int (__cdecl *sys_is_redirected)(int fd);
    int (__cdecl *sys_pipe_alloc)(void);
    void (__cdecl *sys_pipe_free)(int id);
    u8 * (__cdecl *sys_pipe_get_buf)(int id);
    u32 (__cdecl *sys_pipe_get_len)(int id);
    void (__cdecl *sys_pipe_clear)(int id);
    int (__cdecl *sys_redirect_fd_buf)(int fd, u8 *buf, u32 size, u32 len);
    u32 (__cdecl *sys_redirect_get_buf_len)(int fd);
    int (__cdecl *paging_is_present)(u32 addr);
    void (__cdecl *snd_bgm_play)(const char *mml);
    void (__cdecl *snd_bgm_stop)(void);
    int (__cdecl *snd_bgm_is_playing)(void);
    void (__cdecl *snd_se_play)(int se_id);
    void (__cdecl *snd_se_play_raw)(int note, int duration_ticks, int tone);
    void (__cdecl *snd_set_master)(int enable);
    void (__cdecl *snd_bgm_set_persist)(int persist);
    int (__cdecl *kbd_is_pressed)(int scancode);
    void (__cdecl *fm_note_on)(int ch, int note);
    void (__cdecl *fm_note_off)(int ch);
    void (__cdecl *fm_set_tone_num)(int ch, int tone_num);
    void (__cdecl *ssg_tone)(int ch, u16 period);
    void (__cdecl *ssg_volume)(int ch, u8 vol);
    void (__cdecl *ssg_all_off)(void);
    void (__cdecl *mouse_poll)(void *info);
    int (__cdecl *mouse_available)(void);
    void (__cdecl *mouse_set_bounds)(i16 x_min, i16 y_min, i16 x_max, i16 y_max);
    void (__cdecl *tvram_readchar_at)(int x, int y, u16 *code, u8 *attr);
    int (__cdecl *tvram_reverse_cell)(int x, int y);
    void (__cdecl *mouse_cursor_set_mode)(int mode);
    void (__cdecl *mouse_cursor_show)(void);
    void (__cdecl *mouse_cursor_hide)(void);
    int (__cdecl *db_open)(const char *path);
    int (__cdecl *db_close)(int handle);
    int (__cdecl *db_exec)(int handle, const char *sql);
    int (__cdecl *db_prepare)(int handle, const char *sql);
    int (__cdecl *db_step)(int handle);
    int (__cdecl *db_column_int)(int handle, int col);
    const char * (__cdecl *db_column_text)(int handle, int col);
    int (__cdecl *db_finalize)(int handle);
    const char * (__cdecl *db_last_error)(int handle);
    u32 (__cdecl *db_mem_used)(void);
    int (__cdecl *kcg_load_font)(const char *path);
    int (__cdecl *ide_get_info)(int drv, void *info);
    void (__cdecl *sys_get_build_info)(char *buf, int size);
    int (__cdecl *loop_attach)(const char *path, int slot);
    void (__cdecl *loop_detach)(int slot);
    int (__cdecl *loop_status)(int slot, u32 *total, int *bps);
    int (__cdecl *dev_blk_read)(const char *dev_name, u32 lba, int count, void *buf);
    int (__cdecl *dev_blk_write)(const char *dev_name, u32 lba, int count, const void *buf);
    int (__cdecl *ime_switch_dict)(int variant);
    int (__cdecl *ime_user_list)(const char *yomi_prefix, void *out, int max);
    int (__cdecl *ime_user_delete)(const char *yomi, const char *kanji);
    int (__cdecl *ime_user_export)(const char *path);
    int (__cdecl *ime_user_clear)(void);
    int (__cdecl *ime_trygetkey)(void);
    int (__cdecl *v86_selftest)(void);
    int (__cdecl *v86_disktest)(const char *path);
    int (__cdecl *v86_boot)(const char *path);
    int (__cdecl *v86_boot2)(const char *path, const char *second);
    void (__cdecl *gfx_screen_info)(void *out);
    int (__cdecl *gfx_hw_fill_rect)(int x, int y, int w, int h, u8 color);
    int (__cdecl *gfx_hw_blit)(int dx, int dy, int sx, int sy, int w, int h);
    int (__cdecl *gui_call)(u32 op, u32 arg);
    int (__cdecl *gui_register)(void *handler, void *pump);
    int (__cdecl *gfx_stats)(void *out);
    int (__cdecl *gfx_lease_palette)(int first, int count, const u8 *rgb);
    int (__cdecl *sys_switch_shell)(const char *path);
    u32 (__cdecl *kbd_dropped_count)(void);
    int (__cdecl *kbd_trygetrawkey)(void);
    int (__cdecl *ime_feed_key)(int keydata);
    void (__cdecl *ime_set_render)(void *table);
    i32 (__cdecl *exec_start)(const char *cmdline);
    i32 (__cdecl *exec_resume)(i32 app_id, i32 wait_ret);
    i32 (__cdecl *exec_park)(void);
    i32 (__cdecl *exec_kill)(i32 app_id);
    i32 (__cdecl *exec_app_state)(i32 app_id);
    i32 (__cdecl *snd_focus)(int app_id);
    i32 (__cdecl *exec_abort_clear)(void);
    i32 (__cdecl *con_sink_read)(void *buf, u32 cap);
    i32 (__cdecl *con_sink_stat)(u32 *pending, u32 *dropped);
    u32 (__cdecl *sys_ram_kb)(void);
    i32 (__cdecl *kbd_inject)(const u8 *utf8, u32 len);
    u32 (__cdecl *kbd_inject_pending)(void);
    i32 (__cdecl *gfx_screen_owner)(void);
    i32 (__cdecl *launch_req)(const char *cmdline);
    i32 (__cdecl *launch_pending)(void);
    i32 (__cdecl *launch_take)(char *buf, u32 cap, i32 *requester, i32 *kind, i32 *arg);
    i32 (__cdecl *launch_report)(i32 token, i32 rc);
    i32 (__cdecl *launch_poll)(i32 token, i32 *status);
    i32 (__cdecl *launch_cancel)(i32 token);
    i32 (__cdecl *launch_child)(i32 id);
    i32 (__cdecl *sys_yield)(void);
    int (__cdecl *db_open_existing)(const char *path, int writable);
    int (__cdecl *db_prepare_only)(int handle, const char *sql);
    int (__cdecl *db_bind_int)(int handle, int index, int value);
    int (__cdecl *db_bind_text)(int handle, int index, const char *text, int length);
    int (__cdecl *db_bind_blob)(int handle, int index, const void *data, int length);
    int (__cdecl *db_bind_null)(int handle, int index);
    int (__cdecl *db_error_code)(int handle);
    i32 (__cdecl *host_open)(const char *req, u32 len);
    i32 (__cdecl *host_status)(i32 h, u32 *status, u32 *length);
    i32 (__cdecl *host_read)(i32 h, void *buf, u32 cap);
    i32 (__cdecl *host_write)(i32 h, const void *buf, u32 len);
    i32 (__cdecl *host_close)(i32 h);
    int (__cdecl *sys_set_mtime)(const char *path, u32 mtime);
    int (__cdecl *kbd_peekkey)(void);
    int (__cdecl *exec_last_result)(int *kind, int *code);
    int (__cdecl *serial_init_vfast)(u32 baud);
    int (__cdecl *serial_get_status)(u32 *mode, u32 *baud, u32 *fifo);
    int (__cdecl *kbd_trygetchar_local)(void);
    int (__cdecl *pci_count)(void);
    int (__cdecl *pci_get)(u32 idx, void *out);
    u32 (__cdecl *pci_cfg_read32)(u32 bus, u32 dev, u32 fn, u32 reg);
    int (__cdecl *sys_time_now)(u32 *lo, u32 *hi);
    int (__cdecl *pci_bind_info)(u32 idx, void *out);
    int (__cdecl *pcm_open)(u32 rate);
    int (__cdecl *pcm_write)(const void *buf, u32 bytes);
    int (__cdecl *pcm_status)(u32 *free_bytes, u32 *counters);
    int (__cdecl *pcm_close)(void);
    int (__cdecl *pcm_set_volume)(u32 percent);
    int (__cdecl *kbd_diag)(KbdDiag *out);
    int (__cdecl *ext2_format_at)(int drv, u32 start_lba, u32 length);
    int (__cdecl *dev_mount_count)(int drv);
    int (__cdecl *sys_umount_checked)(const char *prefix);
    int (__cdecl *hdd_geom_info)(int drv, HddGeom *out);
    int (__cdecl *boot_image_info)(BootImageInfo *out);
    int (__cdecl *sfs_begin)(void);
    int (__cdecl *sfs_end)(int exit_code);
    int (__cdecl *serial_diag)(SerialDiag *out);
    int (__cdecl *kbd_diag_log)(u32 after_seq, KbdDiagLogEnt *out, int max);
    int (__cdecl *v86_gdc_capture)(int mode, V86Gcap *out);
    /* 予約 (KAPI_FUNC_COUNT..KAPI_FUNC_CAPACITY-1、60 本)。末尾追記はここを削って使う */
    i32 (__cdecl *kapi_reserved[60])(void);
    u32 sbrk_heap_limit;  /* newlib _sbrk用ヒープ上限アドレス (exec_runでセットされる) */
    u32 shm_base;  /* 共有メモリ (MEM_SHM_BASE) の先頭アドレス。DB結果受け渡しに使用 (exec_initでセット) */
} KernelAPI;

#define KAPI_FUNC_COUNT 240
#define KAPI_FUNC_CAPACITY 300
#define KAPI_FUNC_RESERVED 60
#define KAPI_DATA_FIELDS_OFF 0x4B8
#define KAPI_DATA_IDX_SBRK_HEAP_LIMIT 302
#define KAPI_DATA_IDX_SHM_BASE 303
#define OS32_KAPI_LAYOUT_SECTION ".os32_kapi_layout"

/* 配置の刻印 (票 TASK_KAPI_DATA_FIELDS、ヘッダ v3)。ELF の非ロードの
 * セクション .os32_kapi_layout に KAPI_DATA_FIELDS_OFF を 1 語置く。
 * mkos32x.py / mkshlib.py がそれを読んで OS32X ヘッダ v3 の kapi_data_off に
 * 写す (刻印が無ければ生成を断る)。置くのは crt0 (sdk/crt/crt0_c.c) の 1 か所
 * と、crt0 を使わない試験バイナリ・Rust の os32api。ファイルスコープに
 * `OS32_KAPI_LAYOUT_STAMP();` と書く。フラグ "" = 非 alloc なので平らな
 * バイナリには入らない。 */
#define OS32_KAPI_LAYOUT_STAMP() __asm__(".pushsection .os32_kapi_layout,\"\",@progbits\n\t.p2align 2\n\t.long 0x4B8\n\t.popsection")

/* 作り直し忘れの検出 (ユーザー決裁 2026-09-24)。crt の大域変数 `kapi` の
 * 実名を os32_kapi_v63 にする。v62 以前にコンパイルしたオブジェクトは
 * `kapi` を参照したままなので、新しい crt とリンクすると未定義参照で落ちる。
 * カーネル (__KERNEL_BUILD__) は自前の kapi を持つので対象外。 */
#ifndef __KERNEL_BUILD__
#define OS32_KAPI_CRT_SYMBOL os32_kapi_v63
#define kapi os32_kapi_v63
#endif
extern const u16 kapi_argsize[KAPI_FUNC_COUNT];
extern const u16 kapi_argptr[KAPI_FUNC_COUNT];

#endif
