/* AUTOGENERATED FILE - DO NOT EDIT */
#include "os32_kapi_shared.h"
#include "gfx.h"
#include "palette.h"
#include "kbd.h"
#include "exec_heap.h"
#include "kmalloc.h"
#include "paging.h"
#include "rtc.h"
#include "exec.h"
#include "fm.h"
#include "np2sysp.h"
#include "ide.h"
#include "path.h"
#include "tvram.h"
#include "vfs.h"
#include "ext2.h"
#include "serial.h"
#include "console.h"
#include "dev.h"
#include "kcg.h"
#include "sys.h"
#include "kprintf.h"
#include "io.h"
#include "shm.h"
#include "ime.h"
#include "fd_redirect.h"
#include "pipe_buffer.h"
#include "snd_engine.h"
#include "mouse.h"
#include "kapi_db.h"
#include "loop_dev.h"
#include "v86.h"
#include "gui.h"
#include "con_sink.h"
#include "kbd_inject.h"
#include "memory_boot.h"
#include "launch.h"
#include "kapi_host.h"
#include "pci.h"
#include "pcm_cs4231.h"
#include "bootinfo.h"
#include "serialfs.h"
#include "v86_gcap.h"

extern volatile u32 tick_count;
extern void kapi_sys_exit(int status);
extern void kapi_sys_get_build_info(char *buf, int size);
extern int gfx_stats(void *out);
extern int gfx_lease_palette(int first, int count, const u8 *rgb);
extern int kapi_sys_set_mtime(const char *path, u32 mtime);
extern int kapi_sys_time_now(u32 *lo, u32 *hi);
extern int kapi_pci_bind_info(u32 idx, void *out);
extern int kapi_serial_diag(SerialDiag *out);

#include "kapi_profile.h"

#ifdef KAPI_PROFILE
volatile u32 kapi_hits[240];
#endif

/* 各スロットの cdecl 引数バイト数 (固定分)。int 0x80 ディスパッチャが
 * ユーザスタックからこの量をコピーして本物の wrap を呼ぶ (可変長は下限)。 */
const u16 kapi_argsize[KAPI_FUNC_COUNT] = {
    0,  /* gfx_init */
    0,  /* gfx_init_200 */
    0,  /* gfx_shutdown */
    0,  /* gfx_present */
    0,  /* kbd_trygetchar */
    4,  /* mem_alloc */
    4,  /* mem_free */
    0,  /* get_tick */
    8,  /* kprintf (...) */
    4,  /* sys_unlink */
    8,  /* sys_rename */
    4,  /* sys_mkdir */
    12,  /* sys_ls */
    0,  /* kmalloc_total */
    0,  /* kmalloc_used */
    0,  /* kmalloc_free */
    0,  /* paging_enabled */
    4,  /* rtc_read */
    0,  /* tvram_clear */
    16,  /* tvram_putchar_at */
    16,  /* tvram_putkanji_at */
    0,  /* tvram_scroll */
    0,  /* kbd_getchar */
    0,  /* kbd_getkey */
    0,  /* kbd_trygetkey */
    12,  /* sys_mount */
    4,  /* sys_umount */
    4,  /* sys_is_mounted */
    4,  /* sys_chdir */
    0,  /* sys_getcwd */
    4,  /* vfs_devname */
    0,  /* vfs_sync */
    4,  /* sys_rmdir */
    4,  /* serial_init */
    4,  /* serial_puts */
    0,  /* serial_getchar */
    4,  /* serial_putchar */
    0,  /* serial_trygetchar */
    0,  /* serial_is_initialized */
    4,  /* exec_run */
    0,  /* dev_count */
    20,  /* dev_get_info */
    0,  /* fm_startup_sound */
    4,  /* fm_play_mml */
    0,  /* np2_detect */
    8,  /* np2_get_version */
    8,  /* np2_get_cpu */
    8,  /* np2_get_clock */
    8,  /* np2_check_hostdrv */
    0,  /* ide_init */
    4,  /* ide_drive_present */
    8,  /* ide_identify */
    12,  /* ide_read_sector */
    0,  /* path_get_drive */
    0,  /* path_get_cwd */
    4,  /* path_set_drive */
    4,  /* path_set_cwd */
    8,  /* path_parse */
    8,  /* ext2_format */
    0,  /* kcg_init */
    4,  /* kcg_set_scale */
    0,  /* buz_on */
    0,  /* buz_off */
    4,  /* rshell_set_active */
    12,  /* ide_write_sector */
    16,  /* ide_write_sectors */
    0,  /* sys_reboot */
    0,  /* sys_halt */
    8,  /* shell_putchar */
    8,  /* shell_print_utf8 */
    0,  /* console_get_cursor_x */
    0,  /* console_get_cursor_y */
    8,  /* console_set_cursor */
    8,  /* sys_open */
    4,  /* sys_close */
    12,  /* sys_read */
    12,  /* sys_write */
    12,  /* sys_lseek */
    8,  /* console_get_size */
    0,  /* kbd_get_modifiers */
    0,  /* sys_get_mem_kb */
    0,  /* sys_time */
    4,  /* gfx_hardware_scroll */
    16,  /* gfx_present_rect */
    4,  /* sys_exit */
    4,  /* sys_isatty */
    8,  /* sys_stat */
    8,  /* sys_fstat */
    16,  /* gfx_set_palette */
    16,  /* gfx_get_palette */
    4,  /* gfx_get_framebuffer */
    16,  /* gfx_add_dirty_rect */
    0,  /* gfx_present_dirty */
    0,  /* gfx_present_nosync */
    4,  /* gfx_present_raster */
    8,  /* kcg_read_ank */
    8,  /* kcg_read_kanji */
    4,  /* sys_shm_alloc */
    4,  /* sys_shm_lock */
    4,  /* sys_shm_free */
    0,  /* ime_getchar */
    0,  /* ime_trygetchar */
    0,  /* ime_toggle */
    0,  /* ime_is_active */
    4,  /* ime_set_mode */
    0,  /* ime_get_mode */
    0,  /* ime_getkey */
    12,  /* sys_redirect_fd */
    4,  /* sys_reset_redirect */
    4,  /* sys_is_redirected */
    0,  /* sys_pipe_alloc */
    4,  /* sys_pipe_free */
    4,  /* sys_pipe_get_buf */
    4,  /* sys_pipe_get_len */
    4,  /* sys_pipe_clear */
    16,  /* sys_redirect_fd_buf */
    4,  /* sys_redirect_get_buf_len */
    4,  /* paging_is_present */
    4,  /* snd_bgm_play */
    0,  /* snd_bgm_stop */
    0,  /* snd_bgm_is_playing */
    4,  /* snd_se_play */
    12,  /* snd_se_play_raw */
    4,  /* snd_set_master */
    4,  /* snd_bgm_set_persist */
    4,  /* kbd_is_pressed */
    8,  /* fm_note_on */
    4,  /* fm_note_off */
    8,  /* fm_set_tone_num */
    8,  /* ssg_tone */
    8,  /* ssg_volume */
    0,  /* ssg_all_off */
    4,  /* mouse_poll */
    0,  /* mouse_available */
    16,  /* mouse_set_bounds */
    16,  /* tvram_readchar_at */
    8,  /* tvram_reverse_cell */
    4,  /* mouse_cursor_set_mode */
    0,  /* mouse_cursor_show */
    0,  /* mouse_cursor_hide */
    4,  /* db_open */
    4,  /* db_close */
    8,  /* db_exec */
    8,  /* db_prepare */
    4,  /* db_step */
    8,  /* db_column_int */
    8,  /* db_column_text */
    4,  /* db_finalize */
    4,  /* db_last_error */
    0,  /* db_mem_used */
    4,  /* kcg_load_font */
    8,  /* ide_get_info */
    8,  /* sys_get_build_info */
    8,  /* loop_attach */
    4,  /* loop_detach */
    12,  /* loop_status */
    16,  /* dev_blk_read */
    16,  /* dev_blk_write */
    4,  /* ime_switch_dict */
    12,  /* ime_user_list */
    8,  /* ime_user_delete */
    4,  /* ime_user_export */
    0,  /* ime_user_clear */
    0,  /* ime_trygetkey */
    0,  /* v86_selftest */
    4,  /* v86_disktest */
    4,  /* v86_boot */
    8,  /* v86_boot2 */
    4,  /* gfx_screen_info */
    20,  /* gfx_hw_fill_rect */
    24,  /* gfx_hw_blit */
    8,  /* gui_call */
    8,  /* gui_register */
    4,  /* gfx_stats */
    12,  /* gfx_lease_palette */
    4,  /* sys_switch_shell */
    0,  /* kbd_dropped_count */
    0,  /* kbd_trygetrawkey */
    4,  /* ime_feed_key */
    4,  /* ime_set_render */
    4,  /* exec_start */
    8,  /* exec_resume */
    0,  /* exec_park */
    4,  /* exec_kill */
    4,  /* exec_app_state */
    4,  /* snd_focus */
    0,  /* exec_abort_clear */
    8,  /* con_sink_read */
    8,  /* con_sink_stat */
    0,  /* sys_ram_kb */
    8,  /* kbd_inject */
    0,  /* kbd_inject_pending */
    0,  /* gfx_screen_owner */
    4,  /* launch_req */
    0,  /* launch_pending */
    20,  /* launch_take */
    8,  /* launch_report */
    8,  /* launch_poll */
    4,  /* launch_cancel */
    4,  /* launch_child */
    0,  /* sys_yield */
    8,  /* db_open_existing */
    8,  /* db_prepare_only */
    12,  /* db_bind_int */
    16,  /* db_bind_text */
    16,  /* db_bind_blob */
    8,  /* db_bind_null */
    4,  /* db_error_code */
    8,  /* host_open */
    12,  /* host_status */
    12,  /* host_read */
    12,  /* host_write */
    4,  /* host_close */
    8,  /* sys_set_mtime */
    0,  /* kbd_peekkey */
    8,  /* exec_last_result */
    4,  /* serial_init_vfast */
    12,  /* serial_get_status */
    0,  /* kbd_trygetchar_local */
    0,  /* pci_count */
    8,  /* pci_get */
    16,  /* pci_cfg_read32 */
    8,  /* sys_time_now */
    8,  /* pci_bind_info */
    4,  /* pcm_open */
    8,  /* pcm_write */
    8,  /* pcm_status */
    0,  /* pcm_close */
    4,  /* pcm_set_volume */
    4,  /* kbd_diag */
    12,  /* ext2_format_at */
    4,  /* dev_mount_count */
    4,  /* sys_umount_checked */
    8,  /* hdd_geom_info */
    4,  /* boot_image_info */
    0,  /* sfs_begin */
    4,  /* sfs_end */
    4,  /* serial_diag */
    12,  /* kbd_diag_log */
    8,  /* v86_gdc_capture */
};

/* 各スロットの固定引数のうちポインタ型のビットマスク (bit k = 引数 k)。
 * ディスパッチャが wrap 前に範囲検証する引数を示す (可変長はガード担保)。 */
const u16 kapi_argptr[KAPI_FUNC_COUNT] = {
    0x0000,  /* gfx_init */
    0x0000,  /* gfx_init_200 */
    0x0000,  /* gfx_shutdown */
    0x0000,  /* gfx_present */
    0x0000,  /* kbd_trygetchar */
    0x0000,  /* mem_alloc */
    0x0001,  /* mem_free: ptr */
    0x0000,  /* get_tick */
    0x0002,  /* kprintf: fmt */
    0x0001,  /* sys_unlink: path */
    0x0003,  /* sys_rename: oldpath,newpath */
    0x0001,  /* sys_mkdir: path */
    0x0007,  /* sys_ls: path,cb,ctx */
    0x0000,  /* kmalloc_total */
    0x0000,  /* kmalloc_used */
    0x0000,  /* kmalloc_free */
    0x0000,  /* paging_enabled */
    0x0001,  /* rtc_read: rtc_time */
    0x0000,  /* tvram_clear */
    0x0000,  /* tvram_putchar_at */
    0x0000,  /* tvram_putkanji_at */
    0x0000,  /* tvram_scroll */
    0x0000,  /* kbd_getchar */
    0x0000,  /* kbd_getkey */
    0x0000,  /* kbd_trygetkey */
    0x0007,  /* sys_mount: prefix,dev,fs */
    0x0001,  /* sys_umount: prefix */
    0x0001,  /* sys_is_mounted: prefix */
    0x0001,  /* sys_chdir: path */
    0x0000,  /* sys_getcwd */
    0x0001,  /* vfs_devname: prefix */
    0x0000,  /* vfs_sync */
    0x0001,  /* sys_rmdir: path */
    0x0000,  /* serial_init */
    0x0001,  /* serial_puts: s */
    0x0000,  /* serial_getchar */
    0x0000,  /* serial_putchar */
    0x0000,  /* serial_trygetchar */
    0x0000,  /* serial_is_initialized */
    0x0001,  /* exec_run: path */
    0x0000,  /* dev_count */
    0x001A,  /* dev_get_info: name,type,sects */
    0x0000,  /* fm_startup_sound */
    0x0001,  /* fm_play_mml: mml */
    0x0000,  /* np2_detect */
    0x0001,  /* np2_get_version: buf */
    0x0001,  /* np2_get_cpu: buf */
    0x0001,  /* np2_get_clock: buf */
    0x0001,  /* np2_check_hostdrv: buf */
    0x0000,  /* ide_init */
    0x0000,  /* ide_drive_present */
    0x0002,  /* ide_identify: info */
    0x0004,  /* ide_read_sector: buf */
    0x0000,  /* path_get_drive */
    0x0000,  /* path_get_cwd */
    0x0001,  /* path_set_drive: d */
    0x0001,  /* path_set_cwd: p */
    0x0003,  /* path_parse: input,result */
    0x0000,  /* ext2_format */
    0x0000,  /* kcg_init */
    0x0000,  /* kcg_set_scale */
    0x0000,  /* buz_on */
    0x0000,  /* buz_off */
    0x0000,  /* rshell_set_active */
    0x0004,  /* ide_write_sector: buf */
    0x0008,  /* ide_write_sectors: buf */
    0x0000,  /* sys_reboot */
    0x0000,  /* sys_halt */
    0x0000,  /* shell_putchar */
    0x0001,  /* shell_print_utf8: utf8_str */
    0x0000,  /* console_get_cursor_x */
    0x0000,  /* console_get_cursor_y */
    0x0000,  /* console_set_cursor */
    0x0001,  /* sys_open: path */
    0x0000,  /* sys_close */
    0x0002,  /* sys_read: buf */
    0x0002,  /* sys_write: buf */
    0x0000,  /* sys_lseek */
    0x0003,  /* console_get_size: w,h */
    0x0000,  /* kbd_get_modifiers */
    0x0000,  /* sys_get_mem_kb */
    0x0000,  /* sys_time */
    0x0000,  /* gfx_hardware_scroll */
    0x0000,  /* gfx_present_rect */
    0x0000,  /* sys_exit */
    0x0000,  /* sys_isatty */
    0x0003,  /* sys_stat: path,buf */
    0x0002,  /* sys_fstat: buf */
    0x0000,  /* gfx_set_palette */
    0x000E,  /* gfx_get_palette: r,g,b */
    0x0001,  /* gfx_get_framebuffer: fb */
    0x0000,  /* gfx_add_dirty_rect */
    0x0000,  /* gfx_present_dirty */
    0x0000,  /* gfx_present_nosync */
    0x0001,  /* gfx_present_raster: table */
    0x0002,  /* kcg_read_ank: buf */
    0x0002,  /* kcg_read_kanji: buf */
    0x0000,  /* sys_shm_alloc */
    0x0001,  /* sys_shm_lock: ptr */
    0x0001,  /* sys_shm_free: ptr */
    0x0000,  /* ime_getchar */
    0x0000,  /* ime_trygetchar */
    0x0000,  /* ime_toggle */
    0x0000,  /* ime_is_active */
    0x0000,  /* ime_set_mode */
    0x0000,  /* ime_get_mode */
    0x0000,  /* ime_getkey */
    0x0002,  /* sys_redirect_fd: path */
    0x0000,  /* sys_reset_redirect */
    0x0000,  /* sys_is_redirected */
    0x0000,  /* sys_pipe_alloc */
    0x0000,  /* sys_pipe_free */
    0x0000,  /* sys_pipe_get_buf */
    0x0000,  /* sys_pipe_get_len */
    0x0000,  /* sys_pipe_clear */
    0x0002,  /* sys_redirect_fd_buf: buf */
    0x0000,  /* sys_redirect_get_buf_len */
    0x0000,  /* paging_is_present */
    0x0001,  /* snd_bgm_play: mml */
    0x0000,  /* snd_bgm_stop */
    0x0000,  /* snd_bgm_is_playing */
    0x0000,  /* snd_se_play */
    0x0000,  /* snd_se_play_raw */
    0x0000,  /* snd_set_master */
    0x0000,  /* snd_bgm_set_persist */
    0x0000,  /* kbd_is_pressed */
    0x0000,  /* fm_note_on */
    0x0000,  /* fm_note_off */
    0x0000,  /* fm_set_tone_num */
    0x0000,  /* ssg_tone */
    0x0000,  /* ssg_volume */
    0x0000,  /* ssg_all_off */
    0x0001,  /* mouse_poll: info */
    0x0000,  /* mouse_available */
    0x0000,  /* mouse_set_bounds */
    0x000C,  /* tvram_readchar_at: code,attr */
    0x0000,  /* tvram_reverse_cell */
    0x0000,  /* mouse_cursor_set_mode */
    0x0000,  /* mouse_cursor_show */
    0x0000,  /* mouse_cursor_hide */
    0x0001,  /* db_open: path */
    0x0000,  /* db_close */
    0x0002,  /* db_exec: sql */
    0x0002,  /* db_prepare: sql */
    0x0000,  /* db_step */
    0x0000,  /* db_column_int */
    0x0000,  /* db_column_text */
    0x0000,  /* db_finalize */
    0x0000,  /* db_last_error */
    0x0000,  /* db_mem_used */
    0x0001,  /* kcg_load_font: path */
    0x0002,  /* ide_get_info: info */
    0x0001,  /* sys_get_build_info: buf */
    0x0001,  /* loop_attach: path */
    0x0000,  /* loop_detach */
    0x0006,  /* loop_status: total,bps */
    0x0009,  /* dev_blk_read: dev_name,buf */
    0x0009,  /* dev_blk_write: dev_name,buf */
    0x0000,  /* ime_switch_dict */
    0x0003,  /* ime_user_list: yomi_prefix,out */
    0x0003,  /* ime_user_delete: yomi,kanji */
    0x0001,  /* ime_user_export: path */
    0x0000,  /* ime_user_clear */
    0x0000,  /* ime_trygetkey */
    0x0000,  /* v86_selftest */
    0x0001,  /* v86_disktest: path */
    0x0001,  /* v86_boot: path */
    0x0003,  /* v86_boot2: path,second */
    0x0001,  /* gfx_screen_info: out */
    0x0000,  /* gfx_hw_fill_rect */
    0x0000,  /* gfx_hw_blit */
    0x0000,  /* gui_call */
    0x0003,  /* gui_register: handler,pump */
    0x0001,  /* gfx_stats: out */
    0x0004,  /* gfx_lease_palette: rgb */
    0x0001,  /* sys_switch_shell: path */
    0x0000,  /* kbd_dropped_count */
    0x0000,  /* kbd_trygetrawkey */
    0x0000,  /* ime_feed_key */
    0x0001,  /* ime_set_render: table */
    0x0001,  /* exec_start: cmdline */
    0x0000,  /* exec_resume */
    0x0000,  /* exec_park */
    0x0000,  /* exec_kill */
    0x0000,  /* exec_app_state */
    0x0000,  /* snd_focus */
    0x0000,  /* exec_abort_clear */
    0x0001,  /* con_sink_read: buf */
    0x0003,  /* con_sink_stat: pending,dropped */
    0x0000,  /* sys_ram_kb */
    0x0001,  /* kbd_inject: utf8 */
    0x0000,  /* kbd_inject_pending */
    0x0000,  /* gfx_screen_owner */
    0x0001,  /* launch_req: cmdline */
    0x0000,  /* launch_pending */
    0x001D,  /* launch_take: buf,requester,kind,arg */
    0x0000,  /* launch_report */
    0x0002,  /* launch_poll: status */
    0x0000,  /* launch_cancel */
    0x0000,  /* launch_child */
    0x0000,  /* sys_yield */
    0x0001,  /* db_open_existing: path */
    0x0002,  /* db_prepare_only: sql */
    0x0000,  /* db_bind_int */
    0x0004,  /* db_bind_text: text */
    0x0004,  /* db_bind_blob: data */
    0x0000,  /* db_bind_null */
    0x0000,  /* db_error_code */
    0x0001,  /* host_open: req */
    0x0006,  /* host_status: status,length */
    0x0002,  /* host_read: buf */
    0x0002,  /* host_write: buf */
    0x0000,  /* host_close */
    0x0001,  /* sys_set_mtime: path */
    0x0000,  /* kbd_peekkey */
    0x0003,  /* exec_last_result: kind,code */
    0x0000,  /* serial_init_vfast */
    0x0007,  /* serial_get_status: mode,baud,fifo */
    0x0000,  /* kbd_trygetchar_local */
    0x0000,  /* pci_count */
    0x0002,  /* pci_get: out */
    0x0000,  /* pci_cfg_read32 */
    0x0003,  /* sys_time_now: lo,hi */
    0x0002,  /* pci_bind_info: out */
    0x0000,  /* pcm_open */
    0x0001,  /* pcm_write: buf */
    0x0003,  /* pcm_status: free_bytes,counters */
    0x0000,  /* pcm_close */
    0x0000,  /* pcm_set_volume */
    0x0001,  /* kbd_diag: out */
    0x0000,  /* ext2_format_at */
    0x0000,  /* dev_mount_count */
    0x0001,  /* sys_umount_checked: prefix */
    0x0002,  /* hdd_geom_info: out */
    0x0001,  /* boot_image_info: out */
    0x0000,  /* sfs_begin */
    0x0000,  /* sfs_end */
    0x0001,  /* serial_diag: out */
    0x0002,  /* kbd_diag_log: out */
    0x0002,  /* v86_gdc_capture: out */
};

/* ---- 出力ポインタの書き込み可検査 (票 TASK_KAPI_OUTPUT_GUARD) --------
 * OS32 は CR0.WP = 0 なので、CPL=0 の wrapper は CPL=3 が渡した
 * 読み取り専用の USER ページ (共有ライブラリの .text/.rodata、全アプリで
 * 同じ物理) にも #PF なしで書ける。ディスパッチャの早期検査
 * (kapi_argptr → ring3_ptr_ok) は帯しか見ないので、**target を呼ぶ前**に
 * ring3_user_ranges_writable で present + RW + USER を確かめる。
 * 断ったら ring3_fault_kill() (戻らない)。CPL=0 の直呼びは素通し。
 *
 * 長さの決め方 (kapi.json の "out" から生成):
 *   NULL          → その範囲は見ない (KAPI ごとの NULL の扱いを変えない)
 *   長さ 0 / 負   → 見ない (target 側も書かないか、既存どおりの扱い)
 *   個数 × 単位   → あふれたら 0xFFFFFFFF (= 必ず拒否) にする
 * 1 回の呼び出しで 2 範囲まで見られるので、3 範囲以上は 2 本ずつに割る
 * (**どれか 1 つでも不可なら 1 バイトも書かない**)。 */
#define KAPI_OUT_LEN(p, n)    ((p) ? (u32)(n) : 0u)
#define KAPI_OUT_LEN_S(p, n)  (((p) && (int)(n) > 0) ? (u32)(n) : 0u)

static u32 kapi_out_mul(u32 n, u32 unit)
{
    if (unit == 0) return 0u;
    if (n > (0xFFFFFFFFUL / unit)) return 0xFFFFFFFFUL;  /* あふれ → 拒否 */
    return n * unit;
}

/* 予約スロット (KAPI_FUNC_COUNT..KAPI_FUNC_CAPACITY-1) の中身。
 * CPL=0 の呼び手 (常駐シェル・--cpl0) は NULL ではなくここへ来る。 */
i32 __cdecl kapi_reserved_nosys(void)
{
    return OS32_ERR_NOSYS;
}

void __cdecl wrap_gfx_init(void)
{
    KAPI_HIT(0);
    gfx_kapi_init();
}

void __cdecl wrap_gfx_init_200(void)
{
    KAPI_HIT(1);
    gfx_kapi_init_200();
}

void __cdecl wrap_gfx_shutdown(void)
{
    KAPI_HIT(2);
    gfx_shutdown();
}

void __cdecl wrap_gfx_present(void)
{
    KAPI_HIT(3);
    gfx_present();
}

int __cdecl wrap_kbd_trygetchar(void)
{
    KAPI_HIT(4);
    return kbd_trygetchar();
}

void * __cdecl wrap_mem_alloc(u32 size)
{
    KAPI_HIT(5);
    return exec_heap_alloc(size);
}

void __cdecl wrap_mem_free(void *ptr)
{
    KAPI_HIT(6);
    exec_heap_free(ptr);
}

u32 __cdecl wrap_get_tick(void)
{
    KAPI_HIT(7);
    return tick_count;
}

int __cdecl wrap_sys_unlink(const char *path)
{
    KAPI_HIT(9);
    return vfs_rm(path);
}

int __cdecl wrap_sys_rename(const char *oldpath, const char *newpath)
{
    KAPI_HIT(10);
    return vfs_rename(oldpath, newpath);
}

int __cdecl wrap_sys_mkdir(const char *path)
{
    KAPI_HIT(11);
    return vfs_mkdir(path);
}

int __cdecl wrap_sys_ls(const char *path, void *cb, void *ctx)
{
    KAPI_HIT(12);
    return vfs_ls(path, (vfs_dir_cb)cb, ctx);
}

u32 __cdecl wrap_kmalloc_total(void)
{
    KAPI_HIT(13);
    return kmalloc_total();
}

u32 __cdecl wrap_kmalloc_used(void)
{
    KAPI_HIT(14);
    return kmalloc_used();
}

u32 __cdecl wrap_kmalloc_free(void)
{
    KAPI_HIT(15);
    return kmalloc_free();
}

int __cdecl wrap_paging_enabled(void)
{
    KAPI_HIT(16);
    return paging_enabled();
}

void __cdecl wrap_rtc_read(void *rtc_time)
{
    KAPI_HIT(17);
    /* 出力範囲が書けるか (票 TASK_KAPI_OUTPUT_GUARD) */
    if (!ring3_user_ranges_writable((u32)rtc_time, KAPI_OUT_LEN(rtc_time, sizeof(RTC_Time)),
                                    (u32)0, 0u)) {
        ring3_fault_kill();   /* 戻らない */
    }
    rtc_read((RTC_Time *)rtc_time);
}

void __cdecl wrap_tvram_clear(void)
{
    KAPI_HIT(18);
    tvram_clear();
}

void __cdecl wrap_tvram_putchar_at(int x, int y, char ch, u8 attr)
{
    KAPI_HIT(19);
    tvram_putchar_at(x, y, ch, attr);
}

void __cdecl wrap_tvram_putkanji_at(int x, int y, u16 jis, u8 attr)
{
    KAPI_HIT(20);
    tvram_putkanji_at(x, y, jis, attr);
}

void __cdecl wrap_tvram_scroll(void)
{
    KAPI_HIT(21);
    tvram_scroll();
}

int __cdecl wrap_kbd_getchar(void)
{
    KAPI_HIT(22);
    return kbd_getchar();
}

int __cdecl wrap_kbd_getkey(void)
{
    KAPI_HIT(23);
    return kbd_getkey();
}

int __cdecl wrap_kbd_trygetkey(void)
{
    KAPI_HIT(24);
    return kbd_trygetkey();
}

int __cdecl wrap_sys_mount(const char *prefix, const char *dev, const char *fs)
{
    KAPI_HIT(25);
    return vfs_mount(prefix, dev, fs);
}

void __cdecl wrap_sys_umount(const char *prefix)
{
    KAPI_HIT(26);
    vfs_umount(prefix);
}

int __cdecl wrap_sys_is_mounted(const char *prefix)
{
    KAPI_HIT(27);
    return vfs_is_mounted(prefix);
}

int __cdecl wrap_sys_chdir(const char *path)
{
    KAPI_HIT(28);
    return vfs_chdir(path);
}

const char * __cdecl wrap_sys_getcwd(void)
{
    KAPI_HIT(29);
    return vfs_cwd_user();
}

const char * __cdecl wrap_vfs_devname(const char *prefix)
{
    KAPI_HIT(30);
    return vfs_devname_user(prefix);
}

int __cdecl wrap_vfs_sync(void)
{
    KAPI_HIT(31);
    return vfs_sync();
}

int __cdecl wrap_sys_rmdir(const char *path)
{
    KAPI_HIT(32);
    return vfs_rmdir(path);
}

void __cdecl wrap_serial_init(u32 baud)
{
    KAPI_HIT(33);
    serial_init(baud);
}

void __cdecl wrap_serial_puts(const char *s)
{
    KAPI_HIT(34);
    serial_puts(s);
}

int __cdecl wrap_serial_getchar(void)
{
    KAPI_HIT(35);
    return serial_getchar();
}

int __cdecl wrap_serial_putchar(u8 ch)
{
    KAPI_HIT(36);
    return serial_putchar(ch);
}

int __cdecl wrap_serial_trygetchar(void)
{
    KAPI_HIT(37);
    return serial_trygetchar();
}

int __cdecl wrap_serial_is_initialized(void)
{
    KAPI_HIT(38);
    return serial_is_initialized();
}

int __cdecl wrap_exec_run(const char *path)
{
    KAPI_HIT(39);
    return exec_run(path);
}

int __cdecl wrap_dev_count(void)
{
    KAPI_HIT(40);
    return dev_count();
}

int __cdecl wrap_dev_get_info(int idx, char *name, int nm, int *type, u32 *sects)
{
    KAPI_HIT(41);
    /* 出力範囲が書けるか (票 TASK_KAPI_OUTPUT_GUARD) */
    if (!ring3_user_ranges_writable((u32)name, KAPI_OUT_LEN_S(name, nm),
                                    (u32)type, KAPI_OUT_LEN(type, sizeof(int))) ||
        !ring3_user_ranges_writable((u32)sects, KAPI_OUT_LEN(sects, sizeof(u32)),
                                    (u32)0, 0u)) {
        ring3_fault_kill();   /* 戻らない */
    }
    { if (!name || nm <= 0) return -1; return dev_api_get_info(idx, name, nm, type, sects); }
}

void __cdecl wrap_fm_startup_sound(void)
{
    KAPI_HIT(42);
    fm_startup_sound();
}

void __cdecl wrap_fm_play_mml(const char *mml)
{
    KAPI_HIT(43);
    fm_play_mml(mml);
}

int __cdecl wrap_np2_detect(void)
{
    KAPI_HIT(44);
    return np2_detect();
}

void __cdecl wrap_np2_get_version(char *buf, int size)
{
    KAPI_HIT(45);
    /* 出力範囲が書けるか (票 TASK_KAPI_OUTPUT_GUARD) */
    if (!ring3_user_ranges_writable((u32)buf, KAPI_OUT_LEN_S(buf, size),
                                    (u32)0, 0u)) {
        ring3_fault_kill();   /* 戻らない */
    }
    np2_get_version(buf, size);
}

void __cdecl wrap_np2_get_cpu(char *buf, int size)
{
    KAPI_HIT(46);
    /* 出力範囲が書けるか (票 TASK_KAPI_OUTPUT_GUARD) */
    if (!ring3_user_ranges_writable((u32)buf, KAPI_OUT_LEN_S(buf, size),
                                    (u32)0, 0u)) {
        ring3_fault_kill();   /* 戻らない */
    }
    np2_get_cpu(buf, size);
}

void __cdecl wrap_np2_get_clock(char *buf, int size)
{
    KAPI_HIT(47);
    /* 出力範囲が書けるか (票 TASK_KAPI_OUTPUT_GUARD) */
    if (!ring3_user_ranges_writable((u32)buf, KAPI_OUT_LEN_S(buf, size),
                                    (u32)0, 0u)) {
        ring3_fault_kill();   /* 戻らない */
    }
    np2_get_clock(buf, size);
}

int __cdecl wrap_np2_check_hostdrv(char *buf, int size)
{
    KAPI_HIT(48);
    /* 出力範囲が書けるか (票 TASK_KAPI_OUTPUT_GUARD) */
    if (!ring3_user_ranges_writable((u32)buf, KAPI_OUT_LEN_S(buf, size),
                                    (u32)0, 0u)) {
        ring3_fault_kill();   /* 戻らない */
    }
    return np2_check_hostdrv(buf, size);
}

void __cdecl wrap_ide_init(void)
{
    KAPI_HIT(49);
    ide_init();
}

int __cdecl wrap_ide_drive_present(int drv)
{
    KAPI_HIT(50);
    return ide_drive_present(drv);
}

int __cdecl wrap_ide_identify(int drv, void *info)
{
    KAPI_HIT(51);
    /* 出力範囲が書けるか (票 TASK_KAPI_OUTPUT_GUARD) */
    if (!ring3_user_ranges_writable((u32)info, KAPI_OUT_LEN(info, sizeof(IdeInfo)),
                                    (u32)0, 0u)) {
        ring3_fault_kill();   /* 戻らない */
    }
    return ide_identify(drv, (IdeInfo *)info);
}

int __cdecl wrap_ide_read_sector(int drv, u32 lba, void *buf)
{
    KAPI_HIT(52);
    /* 出力範囲が書けるか (票 TASK_KAPI_OUTPUT_GUARD) */
    if (!ring3_user_ranges_writable((u32)buf, KAPI_OUT_LEN(buf, 512u),
                                    (u32)0, 0u)) {
        ring3_fault_kill();   /* 戻らない */
    }
    return ide_read_sector(drv, lba, buf);
}

const char * __cdecl wrap_path_get_drive(void)
{
    KAPI_HIT(53);
    return path_get_drive_user();
}

const char * __cdecl wrap_path_get_cwd(void)
{
    KAPI_HIT(54);
    return path_get_cwd_user();
}

int __cdecl wrap_path_set_drive(const char *d)
{
    KAPI_HIT(55);
    return path_set_drive(d);
}

void __cdecl wrap_path_set_cwd(const char *p)
{
    KAPI_HIT(56);
    path_set_cwd(p);
}

void __cdecl wrap_path_parse(const char *input, void *result)
{
    KAPI_HIT(57);
    /* 出力範囲が書けるか (票 TASK_KAPI_OUTPUT_GUARD) */
    if (!ring3_user_ranges_writable((u32)result, KAPI_OUT_LEN(result, sizeof(ParsedPath)),
                                    (u32)0, 0u)) {
        ring3_fault_kill();   /* 戻らない */
    }
    path_parse(input, (ParsedPath *)result);
}

int __cdecl wrap_ext2_format(int drv, u32 sectors)
{
    KAPI_HIT(58);
    return ext2_format(drv, sectors);
}

void __cdecl wrap_kcg_init(void)
{
    KAPI_HIT(59);
    kcg_init();
}

void __cdecl wrap_kcg_set_scale(int s)
{
    KAPI_HIT(60);
    kcg_set_scale(s);
}

void __cdecl wrap_buz_on(void)
{
    KAPI_HIT(61);
    buz_on();
}

void __cdecl wrap_buz_off(void)
{
    KAPI_HIT(62);
    buz_off();
}

void __cdecl wrap_rshell_set_active(int active)
{
    KAPI_HIT(63);
    rshell_active = active;
}

int __cdecl wrap_ide_write_sector(int drv, u32 lba, const void *buf)
{
    KAPI_HIT(64);
    return ide_write_sector(drv, lba, buf);
}

int __cdecl wrap_ide_write_sectors(int drv, u32 lba, u32 cnt, const void *buf)
{
    KAPI_HIT(65);
    return ide_write_sectors(drv, lba, cnt, buf);
}

void __cdecl wrap_sys_reboot(void)
{
    KAPI_HIT(66);
    sys_reboot();
}

void __cdecl wrap_sys_halt(void)
{
    KAPI_HIT(67);
    sys_halt();
}

void __cdecl wrap_shell_putchar(char ch, u8 attr)
{
    KAPI_HIT(68);
    shell_putchar(ch, attr);
}

void __cdecl wrap_shell_print_utf8(const char *utf8_str, u8 color)
{
    KAPI_HIT(69);
    shell_print_utf8(utf8_str, color);
}

int __cdecl wrap_console_get_cursor_x(void)
{
    KAPI_HIT(70);
    return console_get_cursor_x();
}

int __cdecl wrap_console_get_cursor_y(void)
{
    KAPI_HIT(71);
    return console_get_cursor_y();
}

void __cdecl wrap_console_set_cursor(int x, int y)
{
    KAPI_HIT(72);
    console_set_cursor(x, y);
}

int __cdecl wrap_sys_open(const char *path, int mode)
{
    KAPI_HIT(73);
    return vfs_open(path, mode);
}

void __cdecl wrap_sys_close(int fd)
{
    KAPI_HIT(74);
    vfs_close(fd);
}

int __cdecl wrap_sys_read(int fd, void *buf, u32 size)
{
    KAPI_HIT(75);
    /* 出力範囲が書けるか (票 TASK_KAPI_OUTPUT_GUARD) */
    if (!ring3_user_ranges_writable((u32)buf, KAPI_OUT_LEN(buf, size),
                                    (u32)0, 0u)) {
        ring3_fault_kill();   /* 戻らない */
    }
    return vfs_read_fd(fd, buf, size);
}

int __cdecl wrap_sys_write(int fd, const void *buf, u32 size)
{
    KAPI_HIT(76);
    return vfs_write_fd(fd, buf, size);
}

int __cdecl wrap_sys_lseek(int fd, int offset, int whence)
{
    KAPI_HIT(77);
    return vfs_seek(fd, offset, whence);
}

void __cdecl wrap_console_get_size(int *w, int *h)
{
    KAPI_HIT(78);
    /* 出力範囲が書けるか (票 TASK_KAPI_OUTPUT_GUARD) */
    if (!ring3_user_ranges_writable((u32)w, KAPI_OUT_LEN(w, sizeof(int)),
                                    (u32)h, KAPI_OUT_LEN(h, sizeof(int)))) {
        ring3_fault_kill();   /* 戻らない */
    }
    console_get_size(w, h);
}

u32 __cdecl wrap_kbd_get_modifiers(void)
{
    KAPI_HIT(79);
    return kbd_get_modifiers();
}

u32 __cdecl wrap_sys_get_mem_kb(void)
{
    KAPI_HIT(80);
    return sys_get_mem_kb();
}

os_time_t __cdecl wrap_sys_time(void)
{
    KAPI_HIT(81);
    return sys_time();
}

void __cdecl wrap_gfx_hardware_scroll(int lines)
{
    KAPI_HIT(82);
    gfx_hardware_scroll(lines);
}

void __cdecl wrap_gfx_present_rect(int x, int y, int w, int h)
{
    KAPI_HIT(83);
    gfx_present_rect(x, y, w, h);
}

void __cdecl wrap_sys_exit(int status)
{
    KAPI_HIT(84);
    kapi_sys_exit(status);
}

int __cdecl wrap_sys_isatty(int fd)
{
    KAPI_HIT(85);
    return vfs_isatty(fd);
}

int __cdecl wrap_sys_stat(const char *path, OS32_Stat *buf)
{
    KAPI_HIT(86);
    /* 出力範囲が書けるか (票 TASK_KAPI_OUTPUT_GUARD) */
    if (!ring3_user_ranges_writable((u32)buf, KAPI_OUT_LEN(buf, sizeof(OS32_Stat)),
                                    (u32)0, 0u)) {
        ring3_fault_kill();   /* 戻らない */
    }
    return vfs_stat(path, buf);
}

int __cdecl wrap_sys_fstat(int fd, OS32_Stat *buf)
{
    KAPI_HIT(87);
    /* 出力範囲が書けるか (票 TASK_KAPI_OUTPUT_GUARD) */
    if (!ring3_user_ranges_writable((u32)buf, KAPI_OUT_LEN(buf, sizeof(OS32_Stat)),
                                    (u32)0, 0u)) {
        ring3_fault_kill();   /* 戻らない */
    }
    return vfs_fstat(fd, buf);
}

void __cdecl wrap_gfx_set_palette(int idx, u8 r, u8 g, u8 b)
{
    KAPI_HIT(88);
    gfx_set_palette_hal(idx, r, g, b);
}

void __cdecl wrap_gfx_get_palette(int idx, u8 *r, u8 *g, u8 *b)
{
    KAPI_HIT(89);
    /* 出力範囲が書けるか (票 TASK_KAPI_OUTPUT_GUARD) */
    if (!ring3_user_ranges_writable((u32)r, KAPI_OUT_LEN(r, sizeof(u8)),
                                    (u32)g, KAPI_OUT_LEN(g, sizeof(u8))) ||
        !ring3_user_ranges_writable((u32)b, KAPI_OUT_LEN(b, sizeof(u8)),
                                    (u32)0, 0u)) {
        ring3_fault_kill();   /* 戻らない */
    }
    palette_get(idx, r, g, b);
}

void __cdecl wrap_gfx_get_framebuffer(void *fb)
{
    KAPI_HIT(90);
    /* 出力範囲が書けるか (票 TASK_KAPI_OUTPUT_GUARD) */
    if (!ring3_user_ranges_writable((u32)fb, KAPI_OUT_LEN(fb, sizeof(GFX_Framebuffer)),
                                    (u32)0, 0u)) {
        ring3_fault_kill();   /* 戻らない */
    }
    gfx_get_framebuffer(fb);
}

void __cdecl wrap_gfx_add_dirty_rect(int x, int y, int w, int h)
{
    KAPI_HIT(91);
    gfx_add_dirty_rect(x, y, w, h);
}

void __cdecl wrap_gfx_present_dirty(void)
{
    KAPI_HIT(92);
    gfx_present_dirty();
}

void __cdecl wrap_gfx_present_nosync(void)
{
    KAPI_HIT(93);
    gfx_present_nosync();
}

void __cdecl wrap_gfx_present_raster(void *table)
{
    KAPI_HIT(94);
    gfx_present_raster((GFX_RasterPalTable *)table);
}

void __cdecl wrap_kcg_read_ank(u8 ch, u8 *buf)
{
    KAPI_HIT(95);
    /* 出力範囲が書けるか (票 TASK_KAPI_OUTPUT_GUARD) */
    if (!ring3_user_ranges_writable((u32)buf, KAPI_OUT_LEN(buf, KCG_ANK_H),
                                    (u32)0, 0u)) {
        ring3_fault_kill();   /* 戻らない */
    }
    kcg_read_ank(ch, buf);
}

void __cdecl wrap_kcg_read_kanji(u16 jis_code, u8 *buf)
{
    KAPI_HIT(96);
    /* 出力範囲が書けるか (票 TASK_KAPI_OUTPUT_GUARD) */
    if (!ring3_user_ranges_writable((u32)buf, KAPI_OUT_LEN(buf, (KCG_KANJI_H * 2)),
                                    (u32)0, 0u)) {
        ring3_fault_kill();   /* 戻らない */
    }
    kcg_read_kanji(jis_code, buf);
}

void * __cdecl wrap_sys_shm_alloc(int blocks)
{
    KAPI_HIT(97);
    return shm_alloc(blocks);
}

int __cdecl wrap_sys_shm_lock(void *ptr)
{
    KAPI_HIT(98);
    return shm_lock(ptr);
}

int __cdecl wrap_sys_shm_free(void *ptr)
{
    KAPI_HIT(99);
    return shm_free(ptr);
}

int __cdecl wrap_ime_getchar(void)
{
    KAPI_HIT(100);
    return ime_getchar();
}

int __cdecl wrap_ime_trygetchar(void)
{
    KAPI_HIT(101);
    return ime_trygetchar();
}

void __cdecl wrap_ime_toggle(void)
{
    KAPI_HIT(102);
    ime_toggle();
}

int __cdecl wrap_ime_is_active(void)
{
    KAPI_HIT(103);
    return ime_is_active();
}

void __cdecl wrap_ime_set_mode(int mode)
{
    KAPI_HIT(104);
    ime_set_mode(mode);
}

int __cdecl wrap_ime_get_mode(void)
{
    KAPI_HIT(105);
    return ime_get_mode();
}

int __cdecl wrap_ime_getkey(void)
{
    KAPI_HIT(106);
    return ime_getkey();
}

int __cdecl wrap_sys_redirect_fd(int fd, const char *path, int mode)
{
    KAPI_HIT(107);
    return fd_redirect_to_file(fd, path, mode);
}

void __cdecl wrap_sys_reset_redirect(int fd)
{
    KAPI_HIT(108);
    fd_redirect_reset(fd);
}

int __cdecl wrap_sys_is_redirected(int fd)
{
    KAPI_HIT(109);
    return fd_is_redirected(fd);
}

int __cdecl wrap_sys_pipe_alloc(void)
{
    KAPI_HIT(110);
    return pipe_alloc();
}

void __cdecl wrap_sys_pipe_free(int id)
{
    KAPI_HIT(111);
    pipe_free(id);
}

u8 * __cdecl wrap_sys_pipe_get_buf(int id)
{
    KAPI_HIT(112);
    return pipe_get_buf(id);
}

u32 __cdecl wrap_sys_pipe_get_len(int id)
{
    KAPI_HIT(113);
    return pipe_get_len(id);
}

void __cdecl wrap_sys_pipe_clear(int id)
{
    KAPI_HIT(114);
    pipe_clear(id);
}

int __cdecl wrap_sys_redirect_fd_buf(int fd, u8 *buf, u32 size, u32 len)
{
    KAPI_HIT(115);
    /* 出力範囲が書けるか (票 TASK_KAPI_OUTPUT_GUARD) */
    if (!ring3_user_ranges_writable((u32)buf, KAPI_OUT_LEN(buf, size),
                                    (u32)0, 0u)) {
        ring3_fault_kill();   /* 戻らない */
    }
    { if (len > size) return -1; return fd_redirect_to_buffer(fd, buf, size, len); }
}

u32 __cdecl wrap_sys_redirect_get_buf_len(int fd)
{
    KAPI_HIT(116);
    return fd_redirect_get_buf_len(fd);
}

int __cdecl wrap_paging_is_present(u32 addr)
{
    KAPI_HIT(117);
    return paging_is_present(addr);
}

void __cdecl wrap_snd_bgm_play(const char *mml)
{
    KAPI_HIT(118);
    snd_bgm_play(mml);
}

void __cdecl wrap_snd_bgm_stop(void)
{
    KAPI_HIT(119);
    snd_bgm_stop();
}

int __cdecl wrap_snd_bgm_is_playing(void)
{
    KAPI_HIT(120);
    return snd_bgm_is_playing();
}

void __cdecl wrap_snd_se_play(int se_id)
{
    KAPI_HIT(121);
    snd_se_play(se_id);
}

void __cdecl wrap_snd_se_play_raw(int note, int duration_ticks, int tone)
{
    KAPI_HIT(122);
    snd_se_play_raw(note, duration_ticks, tone);
}

void __cdecl wrap_snd_set_master(int enable)
{
    KAPI_HIT(123);
    snd_set_master(enable);
}

void __cdecl wrap_snd_bgm_set_persist(int persist)
{
    KAPI_HIT(124);
    snd_bgm_set_persist(persist);
}

int __cdecl wrap_kbd_is_pressed(int scancode)
{
    KAPI_HIT(125);
    return kbd_is_pressed(scancode);
}

void __cdecl wrap_fm_note_on(int ch, int note)
{
    KAPI_HIT(126);
    fm_note_on(ch, note);
}

void __cdecl wrap_fm_note_off(int ch)
{
    KAPI_HIT(127);
    fm_note_off(ch);
}

void __cdecl wrap_fm_set_tone_num(int ch, int tone_num)
{
    KAPI_HIT(128);
    fm_set_tone_num(ch, tone_num);
}

void __cdecl wrap_ssg_tone(int ch, u16 period)
{
    KAPI_HIT(129);
    ssg_tone(ch, period);
}

void __cdecl wrap_ssg_volume(int ch, u8 vol)
{
    KAPI_HIT(130);
    ssg_volume(ch, (uchar)vol);
}

void __cdecl wrap_ssg_all_off(void)
{
    KAPI_HIT(131);
    ssg_all_off();
}

void __cdecl wrap_mouse_poll(void *info)
{
    KAPI_HIT(132);
    /* 出力範囲が書けるか (票 TASK_KAPI_OUTPUT_GUARD) */
    if (!ring3_user_ranges_writable((u32)info, KAPI_OUT_LEN(info, sizeof(MouseState)),
                                    (u32)0, 0u)) {
        ring3_fault_kill();   /* 戻らない */
    }
    mouse_poll((MouseState *)info);
}

int __cdecl wrap_mouse_available(void)
{
    KAPI_HIT(133);
    return mouse_available();
}

void __cdecl wrap_mouse_set_bounds(i16 x_min, i16 y_min, i16 x_max, i16 y_max)
{
    KAPI_HIT(134);
    mouse_set_bounds(x_min, y_min, x_max, y_max);
}

void __cdecl wrap_tvram_readchar_at(int x, int y, u16 *code, u8 *attr)
{
    KAPI_HIT(135);
    /* 出力範囲が書けるか (票 TASK_KAPI_OUTPUT_GUARD) */
    if (!ring3_user_ranges_writable((u32)code, KAPI_OUT_LEN(code, sizeof(u16)),
                                    (u32)attr, KAPI_OUT_LEN(attr, sizeof(u8)))) {
        ring3_fault_kill();   /* 戻らない */
    }
    tvram_readchar_at(x, y, code, attr);
}

int __cdecl wrap_tvram_reverse_cell(int x, int y)
{
    KAPI_HIT(136);
    return tvram_reverse_cell(x, y);
}

void __cdecl wrap_mouse_cursor_set_mode(int mode)
{
    KAPI_HIT(137);
    mouse_cursor_set_mode(mode);
}

void __cdecl wrap_mouse_cursor_show(void)
{
    KAPI_HIT(138);
    mouse_cursor_show();
}

void __cdecl wrap_mouse_cursor_hide(void)
{
    KAPI_HIT(139);
    mouse_cursor_hide();
}

int __cdecl wrap_db_open(const char *path)
{
    KAPI_HIT(140);
    return kapi_db_open(path);
}

int __cdecl wrap_db_close(int handle)
{
    KAPI_HIT(141);
    return kapi_db_close(handle);
}

int __cdecl wrap_db_exec(int handle, const char *sql)
{
    KAPI_HIT(142);
    return kapi_db_exec(handle, sql);
}

int __cdecl wrap_db_prepare(int handle, const char *sql)
{
    KAPI_HIT(143);
    return kapi_db_prepare(handle, sql);
}

int __cdecl wrap_db_step(int handle)
{
    KAPI_HIT(144);
    return kapi_db_step(handle);
}

int __cdecl wrap_db_column_int(int handle, int col)
{
    KAPI_HIT(145);
    return kapi_db_column_int(handle, col);
}

const char * __cdecl wrap_db_column_text(int handle, int col)
{
    KAPI_HIT(146);
    return kapi_db_column_text(handle, col);
}

int __cdecl wrap_db_finalize(int handle)
{
    KAPI_HIT(147);
    return kapi_db_finalize(handle);
}

const char * __cdecl wrap_db_last_error(int handle)
{
    KAPI_HIT(148);
    return kapi_db_last_error(handle);
}

u32 __cdecl wrap_db_mem_used(void)
{
    KAPI_HIT(149);
    return kapi_db_mem_used();
}

int __cdecl wrap_kcg_load_font(const char *path)
{
    KAPI_HIT(150);
    return kcg_load_font(path);
}

int __cdecl wrap_ide_get_info(int drv, void *info)
{
    KAPI_HIT(151);
    /* 出力範囲が書けるか (票 TASK_KAPI_OUTPUT_GUARD) */
    if (!ring3_user_ranges_writable((u32)info, KAPI_OUT_LEN(info, sizeof(IdeInfo)),
                                    (u32)0, 0u)) {
        ring3_fault_kill();   /* 戻らない */
    }
    return ide_get_info(drv, (IdeInfo *)info);
}

void __cdecl wrap_sys_get_build_info(char *buf, int size)
{
    KAPI_HIT(152);
    /* 出力範囲が書けるか (票 TASK_KAPI_OUTPUT_GUARD) */
    if (!ring3_user_ranges_writable((u32)buf, KAPI_OUT_LEN_S(buf, size),
                                    (u32)0, 0u)) {
        ring3_fault_kill();   /* 戻らない */
    }
    kapi_sys_get_build_info(buf, size);
}

int __cdecl wrap_loop_attach(const char *path, int slot)
{
    KAPI_HIT(153);
    return loop_dev_attach(path, slot);
}

void __cdecl wrap_loop_detach(int slot)
{
    KAPI_HIT(154);
    loop_dev_detach(slot);
}

int __cdecl wrap_loop_status(int slot, u32 *total, int *bps)
{
    KAPI_HIT(155);
    /* 出力範囲が書けるか (票 TASK_KAPI_OUTPUT_GUARD) */
    if (!ring3_user_ranges_writable((u32)total, KAPI_OUT_LEN(total, sizeof(u32)),
                                    (u32)bps, KAPI_OUT_LEN(bps, sizeof(int)))) {
        ring3_fault_kill();   /* 戻らない */
    }
    return loop_dev_status(slot, total, bps);
}

int __cdecl wrap_dev_blk_read(const char *dev_name, u32 lba, int count, void *buf)
{
    KAPI_HIT(156);
    { Device *d = dev_find(dev_name); if (!d) return -1; if (count < 0) return -1; if (count > 0 && buf && d->sect_size > 0) { if ((u32)count > 0xFFFFFFFFu / (u32)d->sect_size) return -1; if (!ring3_user_ranges_writable((u32)buf, (u32)count * (u32)d->sect_size, 0, 0)) ring3_fault_kill(); } return dev_blk_read_lba(d, lba, count, buf); }
}

int __cdecl wrap_dev_blk_write(const char *dev_name, u32 lba, int count, const void *buf)
{
    KAPI_HIT(157);
    { Device *d = dev_find(dev_name); if (!d) return -1; return dev_blk_write_lba(d, lba, count, buf); }
}

int __cdecl wrap_ime_switch_dict(int variant)
{
    KAPI_HIT(158);
    return ime_switch_dict(variant);
}

int __cdecl wrap_ime_user_list(const char *yomi_prefix, void *out, int max)
{
    KAPI_HIT(159);
    /* 出力範囲が書けるか (票 TASK_KAPI_OUTPUT_GUARD) */
    if (!ring3_user_ranges_writable(
            (u32)out, kapi_out_mul(KAPI_OUT_LEN_S(out, max), (u32)(sizeof(IME_UserEntry))),
            (u32)0, 0u)) {
        ring3_fault_kill();   /* 戻らない */
    }
    return ime_user_list_facade(yomi_prefix, out, max);
}

int __cdecl wrap_ime_user_delete(const char *yomi, const char *kanji)
{
    KAPI_HIT(160);
    return ime_user_delete_facade(yomi, kanji);
}

int __cdecl wrap_ime_user_export(const char *path)
{
    KAPI_HIT(161);
    return ime_user_export_facade(path);
}

int __cdecl wrap_ime_user_clear(void)
{
    KAPI_HIT(162);
    return ime_user_clear_facade();
}

int __cdecl wrap_ime_trygetkey(void)
{
    KAPI_HIT(163);
    return ime_trygetkey();
}

int __cdecl wrap_v86_selftest(void)
{
    KAPI_HIT(164);
    return v86_smoke_test();
}

int __cdecl wrap_v86_disktest(const char *path)
{
    KAPI_HIT(165);
    return v86_disk_test(path);
}

int __cdecl wrap_v86_boot(const char *path)
{
    KAPI_HIT(166);
    return v86_boot(path);
}

int __cdecl wrap_v86_boot2(const char *path, const char *second)
{
    KAPI_HIT(167);
    return v86_boot2(path, second);
}

void __cdecl wrap_gfx_screen_info(void *out)
{
    KAPI_HIT(168);
    /* 出力範囲が書けるか (票 TASK_KAPI_OUTPUT_GUARD) */
    if (!ring3_user_ranges_writable((u32)out, KAPI_OUT_LEN(out, sizeof(GFX_ScreenInfo)),
                                    (u32)0, 0u)) {
        ring3_fault_kill();   /* 戻らない */
    }
    gfx_screen_info(out);
}

int __cdecl wrap_gfx_hw_fill_rect(int x, int y, int w, int h, u8 color)
{
    KAPI_HIT(169);
    return gfx_hw_fill_rect(x, y, w, h, color);
}

int __cdecl wrap_gfx_hw_blit(int dx, int dy, int sx, int sy, int w, int h)
{
    KAPI_HIT(170);
    return gfx_hw_blit(dx, dy, sx, sy, w, h);
}

int __cdecl wrap_gui_call(u32 op, u32 arg)
{
    KAPI_HIT(171);
    return gui_call(op, arg);
}

int __cdecl wrap_gui_register(void *handler, void *pump)
{
    KAPI_HIT(172);
    return gui_register(handler, pump);
}

int __cdecl wrap_gfx_stats(void *out)
{
    KAPI_HIT(173);
    /* 出力範囲が書けるか (票 TASK_KAPI_OUTPUT_GUARD) */
    if (!ring3_user_ranges_writable((u32)out, KAPI_OUT_LEN(out, sizeof(GFX_Stats)),
                                    (u32)0, 0u)) {
        ring3_fault_kill();   /* 戻らない */
    }
    return gfx_stats(out);
}

int __cdecl wrap_gfx_lease_palette(int first, int count, const u8 *rgb)
{
    KAPI_HIT(174);
    return gfx_lease_palette(first, count, rgb);
}

int __cdecl wrap_sys_switch_shell(const char *path)
{
    KAPI_HIT(175);
    return sys_switch_shell(path);
}

u32 __cdecl wrap_kbd_dropped_count(void)
{
    KAPI_HIT(176);
    return kbd_dropped_count();
}

int __cdecl wrap_kbd_trygetrawkey(void)
{
    KAPI_HIT(177);
    return kbd_trygetrawkey();
}

int __cdecl wrap_ime_feed_key(int keydata)
{
    KAPI_HIT(178);
    return ime_feed_key(keydata);
}

void __cdecl wrap_ime_set_render(void *table)
{
    KAPI_HIT(179);
    gui_ime_set_render(table);
}

i32 __cdecl wrap_exec_start(const char *cmdline)
{
    KAPI_HIT(180);
    return exec_start(cmdline);
}

i32 __cdecl wrap_exec_resume(i32 app_id, i32 wait_ret)
{
    KAPI_HIT(181);
    return exec_resume(app_id, wait_ret);
}

i32 __cdecl wrap_exec_park(void)
{
    KAPI_HIT(182);
    return exec_park();
}

i32 __cdecl wrap_exec_kill(i32 app_id)
{
    KAPI_HIT(183);
    return exec_kill(app_id);
}

i32 __cdecl wrap_exec_app_state(i32 app_id)
{
    KAPI_HIT(184);
    return exec_app_state(app_id);
}

i32 __cdecl wrap_snd_focus(int app_id)
{
    KAPI_HIT(185);
    return snd_focus(app_id);
}

i32 __cdecl wrap_exec_abort_clear(void)
{
    KAPI_HIT(186);
    return exec_abort_clear();
}

i32 __cdecl wrap_con_sink_read(void *buf, u32 cap)
{
    KAPI_HIT(187);
    /* 出力範囲が書けるか (票 TASK_KAPI_OUTPUT_GUARD) */
    if (!ring3_user_ranges_writable((u32)buf, KAPI_OUT_LEN(buf, cap),
                                    (u32)0, 0u)) {
        ring3_fault_kill();   /* 戻らない */
    }
    return con_sink_read(buf, cap);
}

i32 __cdecl wrap_con_sink_stat(u32 *pending, u32 *dropped)
{
    KAPI_HIT(188);
    /* 出力範囲が書けるか (票 TASK_KAPI_OUTPUT_GUARD) */
    if (!ring3_user_ranges_writable((u32)pending, KAPI_OUT_LEN(pending, sizeof(u32)),
                                    (u32)dropped, KAPI_OUT_LEN(dropped, sizeof(u32)))) {
        ring3_fault_kill();   /* 戻らない */
    }
    return con_sink_stat(pending, dropped);
}

u32 __cdecl wrap_sys_ram_kb(void)
{
    KAPI_HIT(189);
    return memory_boot_ram_kb();
}

i32 __cdecl wrap_kbd_inject(const u8 *utf8, u32 len)
{
    KAPI_HIT(190);
    return kbd_inject(utf8, len);
}

u32 __cdecl wrap_kbd_inject_pending(void)
{
    KAPI_HIT(191);
    return kbd_inject_pending();
}

i32 __cdecl wrap_gfx_screen_owner(void)
{
    KAPI_HIT(192);
    return gfx_screen_owner();
}

i32 __cdecl wrap_launch_req(const char *cmdline)
{
    KAPI_HIT(193);
    return launch_req(cmdline);
}

i32 __cdecl wrap_launch_pending(void)
{
    KAPI_HIT(194);
    return launch_pending();
}

i32 __cdecl wrap_launch_take(char *buf, u32 cap, i32 *requester, i32 *kind, i32 *arg)
{
    KAPI_HIT(195);
    /* 出力範囲が書けるか (票 TASK_KAPI_OUTPUT_GUARD) */
    if (!ring3_user_ranges_writable((u32)buf, KAPI_OUT_LEN(buf, cap),
                                    (u32)requester, KAPI_OUT_LEN(requester, sizeof(i32))) ||
        !ring3_user_ranges_writable((u32)kind, KAPI_OUT_LEN(kind, sizeof(i32)),
                                    (u32)arg, KAPI_OUT_LEN(arg, sizeof(i32)))) {
        ring3_fault_kill();   /* 戻らない */
    }
    return launch_take(buf, cap, requester, kind, arg);
}

i32 __cdecl wrap_launch_report(i32 token, i32 rc)
{
    KAPI_HIT(196);
    return launch_report(token, rc);
}

i32 __cdecl wrap_launch_poll(i32 token, i32 *status)
{
    KAPI_HIT(197);
    /* 出力範囲が書けるか (票 TASK_KAPI_OUTPUT_GUARD) */
    if (!ring3_user_ranges_writable((u32)status, KAPI_OUT_LEN(status, sizeof(i32)),
                                    (u32)0, 0u)) {
        ring3_fault_kill();   /* 戻らない */
    }
    return launch_poll(token, status);
}

i32 __cdecl wrap_launch_cancel(i32 token)
{
    KAPI_HIT(198);
    return launch_cancel(token);
}

i32 __cdecl wrap_launch_child(i32 id)
{
    KAPI_HIT(199);
    return launch_child(id);
}

i32 __cdecl wrap_sys_yield(void)
{
    KAPI_HIT(200);
    return exec_sys_yield();
}

int __cdecl wrap_db_open_existing(const char *path, int writable)
{
    KAPI_HIT(201);
    return kapi_db_open_existing(path, writable);
}

int __cdecl wrap_db_prepare_only(int handle, const char *sql)
{
    KAPI_HIT(202);
    return kapi_db_prepare_only(handle, sql);
}

int __cdecl wrap_db_bind_int(int handle, int index, int value)
{
    KAPI_HIT(203);
    return kapi_db_bind_int(handle, index, value);
}

int __cdecl wrap_db_bind_text(int handle, int index, const char *text, int length)
{
    KAPI_HIT(204);
    return kapi_db_bind_text(handle, index, text, length);
}

int __cdecl wrap_db_bind_blob(int handle, int index, const void *data, int length)
{
    KAPI_HIT(205);
    return kapi_db_bind_blob(handle, index, data, length);
}

int __cdecl wrap_db_bind_null(int handle, int index)
{
    KAPI_HIT(206);
    return kapi_db_bind_null(handle, index);
}

int __cdecl wrap_db_error_code(int handle)
{
    KAPI_HIT(207);
    return kapi_db_error_code(handle);
}

i32 __cdecl wrap_host_open(const char *req, u32 len)
{
    KAPI_HIT(208);
    return kapi_host_open(req, len);
}

i32 __cdecl wrap_host_status(i32 h, u32 *status, u32 *length)
{
    KAPI_HIT(209);
    /* 出力範囲が書けるか (票 TASK_KAPI_OUTPUT_GUARD) */
    if (!ring3_user_ranges_writable((u32)status, KAPI_OUT_LEN(status, sizeof(u32)),
                                    (u32)length, KAPI_OUT_LEN(length, sizeof(u32)))) {
        ring3_fault_kill();   /* 戻らない */
    }
    return kapi_host_status(h, status, length);
}

i32 __cdecl wrap_host_read(i32 h, void *buf, u32 cap)
{
    KAPI_HIT(210);
    /* 出力範囲が書けるか (票 TASK_KAPI_OUTPUT_GUARD) */
    if (!ring3_user_ranges_writable((u32)buf, KAPI_OUT_LEN(buf, cap),
                                    (u32)0, 0u)) {
        ring3_fault_kill();   /* 戻らない */
    }
    return kapi_host_read(h, buf, cap);
}

i32 __cdecl wrap_host_write(i32 h, const void *buf, u32 len)
{
    KAPI_HIT(211);
    return kapi_host_write(h, buf, len);
}

i32 __cdecl wrap_host_close(i32 h)
{
    KAPI_HIT(212);
    return kapi_host_close(h);
}

int __cdecl wrap_sys_set_mtime(const char *path, u32 mtime)
{
    KAPI_HIT(213);
    return kapi_sys_set_mtime(path, mtime);
}

int __cdecl wrap_kbd_peekkey(void)
{
    KAPI_HIT(214);
    return kbd_peekkey();
}

int __cdecl wrap_exec_last_result(int *kind, int *code)
{
    KAPI_HIT(215);
    /* 出力範囲が書けるか (票 TASK_KAPI_OUTPUT_GUARD) */
    if (!ring3_user_ranges_writable((u32)kind, KAPI_OUT_LEN(kind, sizeof(int)),
                                    (u32)code, KAPI_OUT_LEN(code, sizeof(int)))) {
        ring3_fault_kill();   /* 戻らない */
    }
    return exec_last_result(kind, code);
}

int __cdecl wrap_serial_init_vfast(u32 baud)
{
    KAPI_HIT(216);
    return serial_init_vfast(baud);
}

int __cdecl wrap_serial_get_status(u32 *mode, u32 *baud, u32 *fifo)
{
    KAPI_HIT(217);
    /* 出力範囲が書けるか (票 TASK_KAPI_OUTPUT_GUARD) */
    if (!ring3_user_ranges_writable((u32)mode, KAPI_OUT_LEN(mode, sizeof(u32)),
                                    (u32)baud, KAPI_OUT_LEN(baud, sizeof(u32))) ||
        !ring3_user_ranges_writable((u32)fifo, KAPI_OUT_LEN(fifo, sizeof(u32)),
                                    (u32)0, 0u)) {
        ring3_fault_kill();   /* 戻らない */
    }
    return serial_get_status(mode, baud, fifo);
}

int __cdecl wrap_kbd_trygetchar_local(void)
{
    KAPI_HIT(218);
    return kbd_trygetchar_local();
}

int __cdecl wrap_pci_count(void)
{
    KAPI_HIT(219);
    return pci_count();
}

int __cdecl wrap_pci_get(u32 idx, void *out)
{
    KAPI_HIT(220);
    /* 出力範囲が書けるか (票 TASK_KAPI_OUTPUT_GUARD) */
    if (!ring3_user_ranges_writable((u32)out, KAPI_OUT_LEN(out, PCI_DEV_STRUCT_SIZE),
                                    (u32)0, 0u)) {
        ring3_fault_kill();   /* 戻らない */
    }
    return pci_get(idx, out);
}

u32 __cdecl wrap_pci_cfg_read32(u32 bus, u32 dev, u32 fn, u32 reg)
{
    KAPI_HIT(221);
    return pci_cfg_read32(bus, dev, fn, reg);
}

int __cdecl wrap_sys_time_now(u32 *lo, u32 *hi)
{
    KAPI_HIT(222);
    return kapi_sys_time_now(lo, hi);
}

int __cdecl wrap_pci_bind_info(u32 idx, void *out)
{
    KAPI_HIT(223);
    return kapi_pci_bind_info(idx, out);
}

int __cdecl wrap_pcm_open(u32 rate)
{
    KAPI_HIT(224);
    return pcm_open(rate);
}

int __cdecl wrap_pcm_write(const void *buf, u32 bytes)
{
    KAPI_HIT(225);
    { u32 a = (u32)buf;
      int rc = pcm_write_check();
      if (rc != 0) return rc;
      if (buf == 0) return OS32_ERR_INVAL;
      if (a + bytes < a) return OS32_ERR_INVAL;
      if (!ring3_user_range_ok(a, bytes)) return OS32_ERR_INVAL;
      if (bytes < PCM_FRAME_BYTES) return 0;
      return pcm_write(buf, bytes); }
}

int __cdecl wrap_pcm_status(u32 *free_bytes, u32 *counters)
{
    KAPI_HIT(226);
    /* 出力範囲が書けるか (票 TASK_KAPI_OUTPUT_GUARD) */
    if (!ring3_user_ranges_writable((u32)free_bytes, KAPI_OUT_LEN(free_bytes, sizeof(u32)),
                                    (u32)counters, KAPI_OUT_LEN(counters, sizeof(u32)))) {
        ring3_fault_kill();   /* 戻らない */
    }
    return pcm_status(free_bytes, counters);
}

int __cdecl wrap_pcm_close(void)
{
    KAPI_HIT(227);
    return pcm_close();
}

int __cdecl wrap_pcm_set_volume(u32 percent)
{
    KAPI_HIT(228);
    return pcm_set_volume(percent);
}

int __cdecl wrap_kbd_diag(KbdDiag *out)
{
    KAPI_HIT(229);
    /* 出力範囲が書けるか (票 TASK_KAPI_OUTPUT_GUARD) */
    if (!ring3_user_ranges_writable((u32)out, KAPI_OUT_LEN(out, sizeof(KbdDiag)),
                                    (u32)0, 0u)) {
        ring3_fault_kill();   /* 戻らない */
    }
    return kbd_diag(out);
}

int __cdecl wrap_ext2_format_at(int drv, u32 start_lba, u32 length)
{
    KAPI_HIT(230);
    return ext2_format_at(drv, start_lba, length);
}

int __cdecl wrap_dev_mount_count(int drv)
{
    KAPI_HIT(231);
    return vfs_dev_mount_count(drv);
}

int __cdecl wrap_sys_umount_checked(const char *prefix)
{
    KAPI_HIT(232);
    return vfs_umount_checked(prefix);
}

int __cdecl wrap_hdd_geom_info(int drv, HddGeom *out)
{
    KAPI_HIT(233);
    /* 出力範囲が書けるか (票 TASK_KAPI_OUTPUT_GUARD) */
    if (!ring3_user_ranges_writable((u32)out, KAPI_OUT_LEN(out, sizeof(HddGeom)),
                                    (u32)0, 0u)) {
        ring3_fault_kill();   /* 戻らない */
    }
    return hdd_geom_info(drv, (void *)out);
}

int __cdecl wrap_boot_image_info(BootImageInfo *out)
{
    KAPI_HIT(234);
    /* 出力範囲が書けるか (票 TASK_KAPI_OUTPUT_GUARD) */
    if (!ring3_user_ranges_writable((u32)out, KAPI_OUT_LEN(out, sizeof(BootImageInfo)),
                                    (u32)0, 0u)) {
        ring3_fault_kill();   /* 戻らない */
    }
    return boot_image_info((void *)out);
}

int __cdecl wrap_sfs_begin(void)
{
    KAPI_HIT(235);
    return serialfs_session_begin();
}

int __cdecl wrap_sfs_end(int exit_code)
{
    KAPI_HIT(236);
    return serialfs_session_end(exit_code);
}

int __cdecl wrap_serial_diag(SerialDiag *out)
{
    KAPI_HIT(237);
    /* 出力範囲が書けるか (票 TASK_KAPI_OUTPUT_GUARD) */
    if (!ring3_user_ranges_writable((u32)out, KAPI_OUT_LEN(out, sizeof(SerialDiag)),
                                    (u32)0, 0u)) {
        ring3_fault_kill();   /* 戻らない */
    }
    return kapi_serial_diag(out);
}

int __cdecl wrap_kbd_diag_log(u32 after_seq, KbdDiagLogEnt *out, int max)
{
    KAPI_HIT(238);
    /* 出力範囲が書けるか (票 TASK_KAPI_OUTPUT_GUARD) */
    if (!ring3_user_ranges_writable(
            (u32)out, kapi_out_mul(KAPI_OUT_LEN_S(out, max), (u32)(sizeof(KbdDiagLogEnt))),
            (u32)0, 0u)) {
        ring3_fault_kill();   /* 戻らない */
    }
    return kbd_diag_log(after_seq, out, max);
}

int __cdecl wrap_v86_gdc_capture(int mode, V86Gcap *out)
{
    KAPI_HIT(239);
    /* 出力範囲が書けるか (票 TASK_KAPI_OUTPUT_GUARD) */
    if (!ring3_user_ranges_writable((u32)out, KAPI_OUT_LEN(out, sizeof(V86Gcap)),
                                    (u32)0, 0u)) {
        ring3_fault_kill();   /* 戻らない */
    }
    return v86_gdc_capture(mode, out);
}

