#!/usr/bin/env python3
"""
kapi_rust_gen.py — kapi.json から Rust KernelAPI バインディングを自動生成する

使用方法:
    python3 tools/kapi_rust_gen.py

出力:
    programs/rust/os32api/src/kapi_generated.rs

kapi.json のフィールド順序に完全に一致する #[repr(C)] 構造体を生成し、
各関数ポインタに対応する安全ラッパーメソッドを提供する。
"""

import json
import re
import sys
import os

# --- C型 → Rust型 変換テーブル ---
TYPE_MAP = {
    "void":            "()",
    "int":             "i32",
    "u8":              "u8",
    "u16":             "u16",
    "u32":             "u32",
    "i16":             "i16",
    "i32":             "i32",
    "char":            "u8",
    "os_time_t":       "u32",
    "const char *":    "*const u8",
    "char *":          "*mut u8",
    "const void *":    "*const u8",
    "void *":          "*mut u8",
    "u8 *":            "*mut u8",
    "const u8 *":      "*const u8",
    "u16 *":           "*mut u16",
    "int *":           "*mut i32",
    "i32 *":           "*mut i32",
    "u32 *":           "*mut u32",
    "OS32_Stat *":     "*mut u8",
}


def c_type_to_rust(c_type):
    """C型文字列をRust型文字列に変換する"""
    c_type = c_type.strip()
    if c_type in TYPE_MAP:
        return TYPE_MAP[c_type]
    # ポインタ型の汎用処理
    if c_type.endswith("*"):
        return "*mut u8"
    return "u32"


# Rust のキーワードのうち、**C の識別子として現れ得る**もの。C 自身の
# キーワード (if / for / struct …) は C の引数名にならないので載せない。
# r# を付ければ識別子として使える (raw identifier)。
RUST_KEYWORDS = frozenset((
    "abstract", "as", "async", "await", "become", "box", "do", "dyn",
    "final", "fn", "impl", "in", "let", "loop", "macro", "match", "mod",
    "move", "mut", "override", "priv", "pub", "ref", "trait", "try",
    "type", "typeof", "unsized", "use", "virtual", "where", "yield",
))

# r# を付けられないキーワード (raw identifier にできない)。末尾に _ を足す。
RUST_RAW_UNSAFE = frozenset(("crate", "self", "Self", "super"))


def parse_arg(arg_str):
    """
    C引数文字列 (例: "u32 size", "const char *fmt") を
    (name, rust_type) タプルに変換する
    """
    arg_str = arg_str.strip()
    if arg_str == "...":
        return ("...", "...")

    # "const char *fmt" → type="const char *", name="fmt"
    # "u32 size" → type="u32", name="size"
    # "int *type" → type="int *", name="type"
    m = re.match(r'^(.*?)([a-zA-Z_][a-zA-Z0-9_]*)(\s*\[\d*\])?\s*$', arg_str)
    if not m:
        return ("_arg", "u32")
    type_part = m.group(1).strip()
    name = m.group(2)

    # Rust予約語のエスケープ。
    # C では普通の識別子でも Rust ではキーワードのものがある ("type" は
    # 元からここで直していたが、KAPI v57 の pci_cfg_read32 が引数に "fn" を
    # 使って**生成した .rs がコンパイルできなくなった**。1 語ずつ足していると
    # 同じことが起きるので、表で持つ)。
    if name in RUST_RAW_UNSAFE:
        # r# を付けられないキーワード。名前を変えるしかない。
        name = name + "_"
    elif name in RUST_KEYWORDS:
        name = "r#" + name

    rust_type = c_type_to_rust(type_part)
    return (name, rust_type)


def generate_rust(data, output_path):
    """kapi.jsonデータからRustバインディングファイルを生成する"""
    apis = data["api"]
    data_fields = data.get("data_fields", [])

    lines = []
    lines.append("/* AUTOGENERATED FILE - DO NOT EDIT */")
    lines.append("/* kapi.json から kapi_rust_gen.py で生成 */")
    lines.append("")
    lines.append("#![allow(dead_code)]")
    lines.append("#![allow(non_snake_case)]")
    lines.append("")

    # --- KernelAPI 構造体 ---
    lines.append("/// KernelAPI 関数テーブル (os32_kapi_generated.h と同一レイアウト)")
    lines.append("#[repr(C)]")
    lines.append("pub struct KernelAPI {")
    lines.append("    pub magic: u32,")
    lines.append("    pub version: u32,")

    for i, api in enumerate(apis):
        name = api["name"]
        ret = api["ret"]
        args = api.get("args", [])

        # 可変引数関数 (kprintfなど)
        is_variadic = "..." in args

        # 引数リスト構築
        rust_args = []
        for a in args:
            if a == "...":
                break
            pname, ptype = parse_arg(a)
            rust_args.append("{}: {}".format(pname, ptype))

        args_str = ", ".join(rust_args)
        rust_ret = c_type_to_rust(ret)

        if rust_ret == "()":
            ret_str = ""
        else:
            ret_str = " -> {}".format(rust_ret)

        if is_variadic:
            lines.append("    /* idx {:>3} */ pub {}: unsafe extern \"C\" fn({}{}, ...),".format(
                i + 2, name, args_str, ret_str))
        else:
            lines.append("    /* idx {:>3} */ pub {}: unsafe extern \"C\" fn({}){},".format(
                i + 2, name, args_str, ret_str))

    # 予約スロット (票 TASK_KAPI_DATA_FIELDS、KAPI v63)。C の
    # `kapi_reserved[]` と同じ本数の詰め物で、データ欄を 8 + 4R に固定する。
    cap = data["func_capacity"]
    if len(apis) > cap:
        raise SystemExit("kapi_rust_gen: 関数 %d 本が容量 func_capacity=%d を超えた"
                         % (len(apis), cap))
    reserved = cap - len(apis)
    if reserved > 0:
        lines.append("    /* idx {:>3}..{:>3} 予約 (C の kapi_reserved[]) */ "
                     "pub kapi_reserved: [u32; {}],".format(
                         len(apis) + 2, cap + 1, reserved))

    # データフィールド (sbrk_heap_limit等)。8 + 4 × func_capacity に固定。
    for df in data_fields:
        rust_type = c_type_to_rust(df["type"])
        comment = df.get("comment", "")
        lines.append("    pub {}: {},  /* {} */".format(df["name"], rust_type, comment))

    lines.append("}")
    lines.append("")

    # --- 定数 ---
    lines.append("/* KernelAPI マジックナンバー */")
    lines.append("pub const KAPI_MAGIC: u32 = 0x4B415049;  /* \"KAPI\" */")
    lines.append("pub const KAPI_VERSION: u32 = {};".format(data["version"]))
    lines.append("")

    # --- 関数表の容量とデータ欄の固定配置 (票 TASK_KAPI_DATA_FIELDS) ---
    data_off = 8 + 4 * cap
    lines.append("/* 関数表の容量とデータ欄の固定配置 (票 TASK_KAPI_DATA_FIELDS、v63) */")
    lines.append("pub const KAPI_FUNC_COUNT: u32 = {};".format(len(apis)))
    lines.append("pub const KAPI_FUNC_CAPACITY: u32 = {};".format(cap))
    lines.append("pub const KAPI_DATA_FIELDS_OFF: u32 = 0x{:X};".format(data_off))
    lines.append("/// データ欄が固定になった KAPI 版 (= C の OS32X_HDR_V3_MIN_API)。これ未満の")
    lines.append("/// カーネルの KernelAPI はデータ欄が別の位置にある。")
    lines.append("pub const OS32X_HDR_V3_MIN_API: u32 = 63;")
    if data_fields:
        lines.append("#[cfg(target_pointer_width = \"32\")]")
        lines.append("const _: () = assert!(core::mem::offset_of!(KernelAPI, {}) == "
                     "KAPI_DATA_FIELDS_OFF as usize);".format(data_fields[0]["name"]))
    lines.append("")
    lines.append("/* 配置の刻印 (ヘッダ v3)。非ロードの .os32_kapi_layout に 1 語置き、")
    lines.append(" * mkos32x.py / mkshlib.py が OS32X ヘッダの kapi_data_off へ写す。")
    lines.append(" * フラグ \"\" = 非 alloc (平らなバイナリに入らない)。crt0 を持たない")
    lines.append(" * libos32gui.shlib はこの刻印だけで配置を示す。 */")
    lines.append("#[cfg(target_pointer_width = \"32\")]")
    lines.append("core::arch::global_asm!(")
    lines.append("    \".pushsection .os32_kapi_layout,\\\"\\\",@progbits\",")
    lines.append("    \".p2align 2\",")
    lines.append("    \".long 0x{:X}\",".format(data_off))
    lines.append("    \".popsection\",")
    lines.append(");")
    lines.append("")

    # --- テキスト属性定数 ---
    lines.append("/* テキスト属性 (kprintf用) */")
    lines.append("pub const ATTR_WHITE: u8  = 0xE1;")
    lines.append("pub const ATTR_GREEN: u8  = 0xA1;")
    lines.append("pub const ATTR_YELLOW: u8 = 0xC1;")
    lines.append("pub const ATTR_RED: u8    = 0x41;")
    lines.append("pub const ATTR_CYAN: u8   = 0x61;")
    lines.append("")

    # ファイル書き出し
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
        f.write("\n")

    print("  Generated: {} ({} API functions + {} data fields)".format(
        output_path, len(apis), len(data_fields)))


def main():
    json_path = "sdk/kapi.json"
    output_path = "sdk/rust/os32api/src/kapi_generated.rs"

    with open(json_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    generate_rust(data, output_path)


if __name__ == "__main__":
    main()
